version: '3'

services:
  db:
    image: mysql:5.5
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "YourDatabaseName"
      MYSQL_USER: "YourUser"
      MYSQL_PASSWORD: "YourUserPassword"

  php:
    depends_on:
      - db
    build: .
    volumes:
      - ./www:/var/www/html
    ports:
      - "8000:80"
    restart: always

volumes:
  db_data: {}
